<<<<<<< HEAD
# Generated by Django 5.2.13 on 2026-04-22 07:07
=======
# Generated by Django 5.2.13 on 2026-04-21 06:33
>>>>>>> d017417b8cfd1d58a32f9a6c1a751174891f1854

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
<<<<<<< HEAD
                ('phone', models.CharField(max_length=10)),
                ('roll_number', models.CharField(max_length=10)),
                ('maths', models.FloatField()),
                ('science', models.FloatField()),
                ('english', models.FloatField()),
=======
                ('phone', models.IntegerField()),
>>>>>>> d017417b8cfd1d58a32f9a6c1a751174891f1854
                ('start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
